/**
 * Downloads the two UI typefaces and writes a local @font-face sheet.
 *
 * Why self-hosted rather than a Google Fonts <link>: a classroom PC must render
 * correctly with no internet. A CDN-hosted font would silently fall back to
 * system-ui exactly when the school's network is down — which is also the moment
 * a lesson is most likely to need the break timer.
 *
 * Run once at build-prep time: `node scripts/fetch-fonts.mjs`
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(repoRoot, 'web', 'public', 'fonts');
const cssPath = path.join(repoRoot, 'web', 'src', 'styles', 'fonts.css');

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

/**
 * Bitter — a variable slab serif for headlines. Slab was chosen over a high-contrast
 * didone because it holds up at interface sizes and reads as deliberate rather than
 * decorative; and unlike most fashionable display serifs (Fraunces, Instrument
 * Serif, Newsreader) it ships Cyrillic, which this product needs for Russian.
 *
 * Manrope — a variable grotesk for UI text. Geometric, slightly technical, and
 * distinctly not Inter: the brief's biggest single tell of template output.
 */
const FAMILIES = [
  { name: 'Bitter', css: 'Bitter:wght@400..700', slug: 'bitter' },
  { name: 'Manrope', css: 'Manrope:wght@400..800', slug: 'manrope' },
];

/** Latin + Cyrillic covers every string the interface ships. */
const WANTED_SUBSETS = ['cyrillic-ext', 'cyrillic', 'latin-ext', 'latin'];

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f.css}`).join('&')}&display=swap`;

const response = await fetch(url, { headers: { 'user-agent': UA } });
if (!response.ok) throw new Error(`Google Fonts responded ${response.status}`);
const css = await response.text();

/** Splits the stylesheet into { subset, family, weight, src } blocks. */
function parseFaces(source) {
  const faces = [];
  // Each block is preceded by a comment naming its subset.
  const blocks = source.split('/*').slice(1);
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim();
    const body = block.slice(block.indexOf('*/') + 2);
    const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
    const weight = /font-weight:\s*([\d ]+);/.exec(body)?.[1]?.trim();
    const src = /url\((https:[^)]+\.woff2)\)/.exec(body)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(body)?.[1]?.trim();
    if (family && weight && src) faces.push({ subset, family, weight, src, unicodeRange });
  }
  return faces;
}

const faces = parseFaces(css).filter((face) => WANTED_SUBSETS.includes(face.subset));
if (faces.length === 0) throw new Error('No matching @font-face blocks found — did the CSS API change shape?');

mkdirSync(outDir, { recursive: true });

const lines = [
  '/*',
  ' * Self-hosted typefaces. Generated by scripts/fetch-fonts.mjs — do not hand-edit.',
  ' *',
  ' * Slab serif for headlines, grotesk for interface text. Both are variable fonts',
  ' * and both carry Cyrillic, which is why these two and not the more fashionable',
  ' * display serifs: this product ships a Russian interface.',
  ' *',
  ' * Hosted locally so a school PC with no internet still gets the intended',
  " * typography rather than a silent fall back to system-ui.",
  ' */',
  '',
];

let downloaded = 0;
for (const face of faces) {
  const slug = FAMILIES.find((f) => f.name === face.family)?.slug ?? face.family.toLowerCase();
  const filename = `${slug}-${face.subset}.woff2`;
  const target = path.join(outDir, filename);

  const fontResponse = await fetch(face.src, { headers: { 'user-agent': UA } });
  if (!fontResponse.ok) throw new Error(`Failed to download ${face.src}: ${fontResponse.status}`);
  const bytes = Buffer.from(await fontResponse.arrayBuffer());
  writeFileSync(target, bytes);
  downloaded += 1;

  lines.push('@font-face {');
  lines.push(`  font-family: '${face.family}';`);
  lines.push('  font-style: normal;');
  // A variable font file covers the whole range in one file.
  lines.push(`  font-weight: ${face.weight.includes(' ') ? face.weight : `${face.weight} ${face.weight}`};`);
  lines.push('  font-display: swap;');
  lines.push(`  src: url('/fonts/${filename}') format('woff2');`);
  if (face.unicodeRange) lines.push(`  unicode-range: ${face.unicodeRange};`);
  lines.push('}');
  lines.push('');
  console.log(`  ${filename.padEnd(26)} ${(bytes.length / 1024).toFixed(1)} KB  (${face.subset})`);
}

writeFileSync(cssPath, `${lines.join('\n')}\n`, 'utf8');
console.log(`\n  ${downloaded} font files → web/public/fonts/`);
console.log(`  @font-face sheet   → web/src/styles/fonts.css`);
